export type CommandPolicy = "delegate" | "optimize" | "extend";

const OPTIMIZED = new Set(["read", "search", "search:context"]);
const EXTENDED = new Set(["edit", "apply_patch", "write", "copy", "mkdir"]);

export function commandPolicy(command: string | undefined): CommandPolicy {
  if (command && OPTIMIZED.has(command)) return "optimize";
  if (command && EXTENDED.has(command)) return "extend";
  return "delegate";
}

export const NATIVE_SUFFICIENT_COMMANDS = new Set([
  "aliases",
  "append",
  "backlinks",
  "base:create",
  "base:query",
  "base:views",
  "bases",
  "bookmark",
  "bookmarks",
  "command",
  "commands",
  "create",
  "deadends",
  "delete",
  "diff",
  "file",
  "files",
  "folder",
  "folders",
  "help",
  "history",
  "history:list",
  "history:open",
  "history:read",
  "history:restore",
  "homepage",
  "homepage:read",
  "hotkey",
  "hotkeys",
  "links",
  "move",
  "open",
  "orphans",
  "outline",
  "plugin",
  "plugin:disable",
  "plugin:enable",
  "plugin:install",
  "plugin:reload",
  "plugin:uninstall",
  "plugins",
  "plugins:enabled",
  "plugins:restrict",
  "prepend",
  "properties",
  "property:read",
  "property:remove",
  "property:set",
  "quickadd",
  "quickadd:check",
  "quickadd:list",
  "quickadd:run",
  "random",
  "random:read",
  "recents",
  "reload",
  "rename",
  "restart",
  "snippet:disable",
  "snippet:enable",
  "snippets",
  "snippets:enabled",
  "sync",
  "sync:deleted",
  "sync:history",
  "sync:open",
  "sync:read",
  "sync:restore",
  "sync:status",
  "tab:open",
  "tabs",
  "tag",
  "tags",
  "task",
  "tasks",
  "template:insert",
  "template:read",
  "templates",
  "theme",
  "theme:install",
  "theme:set",
  "theme:uninstall",
  "themes",
  "unresolved",
  "vault",
  "vaults",
  "version",
  "wordcount",
  "workspace",
  "dev:cdp",
  "dev:console",
  "dev:css",
  "dev:debug",
  "dev:dom",
  "dev:errors",
  "dev:mobile",
  "dev:screenshot",
  "devtools",
  "eval"
]);

export function implementedCommands(): string[] {
  return [...OPTIMIZED, ...EXTENDED].sort();
}
