export {
  analyzeSearchQuery,
  analyzeSearchText,
  BODY_FULL_ANALYSIS_MAX_CHARS,
  BODY_INDEX_BUDGET_IDENTITY,
  BODY_LEXICAL_SAMPLE_MAX_CHARS,
  BODY_LONG_MAX_CHARS,
  BODY_MORPH_MAX_TOKENS,
  BODY_NGRAM_HUGE_MAX_TERMS,
  BODY_NGRAM_HUGE_SAMPLE_MAX_CHARS,
  BODY_NGRAM_LONG_MAX_TERMS,
  BODY_NGRAM_LONG_SAMPLE_MAX_CHARS,
  BODY_NGRAM_PAPER_MAX_TERMS,
  BODY_NGRAM_SHORT_MAX_TERMS,
  BODY_SAMPLE_WINDOWS,
  BODY_SHORT_MAX_CHARS,
  BODY_SURFACE_MAX_TERMS,
  bodyIndexBudgetForText,
  emptySearchTokenChannels,
  MAX_NGRAM,
  MIN_NGRAM,
  ngramSearchTerms,
  noteLinkTargetPath,
  parseNoteLinks,
  sampleTextWindows,
  SEARCH_TOKEN_CHANNELS,
  searchFieldTokenTexts,
  SNIPPET_DOC_ANALYZED_CHARS_MAX,
  SNIPPET_DOC_ANALYZED_LINES_MAX,
  SNIPPET_LINE_ANALYSIS_MAX_CHARS,
  SNIPPET_LINE_MORPH_MAX_TERMS,
  SNIPPET_LINE_NGRAM_MAX_TERMS,
  SNIPPET_LINE_SURFACE_MAX_TERMS,
  surfaceSearchTerms,
  termsToSearchText,
  tokenChannelsOverlap,
  uniqueSearchTerms,
} from './analysis/index.js';

export type {
  BodyIndexBudget,
  BodyIndexBudgetTier,
  NgramSearchTermOptions,
  ParsedNoteLinkKind,
  ParsedNoteLinks,
  SearchFieldTokenTextOptions,
  SearchFieldTokenTexts,
  SearchTextAnalysis,
  SearchTextAnalysisOptions,
  SearchTokenChannel,
  SearchTokenChannelTerms,
  UnresolvedNoteLink,
} from './analysis/index.js';

export {
  ANALYZER_VERSION,
  CANDIDATE_LIMIT_MIN,
  CANDIDATE_LIMIT_MULTIPLIER,
  COVERAGE_BUCKET_MIN_TERMS,
  COVERAGE_FIELD_WEIGHT,
  DEFAULT_RRF_K,
  EXACT_DOMINANCE_EPSILON,
  EXACT_PRIORITY,
  MAX_SEARCH_QUERY_TERMS_PER_CHANNEL,
  PHRASE_PRIORITY,
  RANK_BUCKET,
  RANK_FINAL_SORT_POLICY,
  RANKING_CONSTANTS,
  SEARCH_BM25_B,
  SEARCH_BM25_D,
  SEARCH_BM25_K1,
  SEARCH_FUZZY_WEIGHT_MULTIPLIER,
  SEARCH_SCORING_LAMBDAS,
  SEARCH_TOKEN_CHANNEL_WEIGHT,
  WEAK_METADATA_COVERAGE_TERMS,
} from './constants.js';

export type { CoverageField, SearchScoringLambdas } from './constants.js';

export { SEARCH_EXPLAIN_TRACE_SCHEMA_VERSION } from './contracts.js';

export type {
  CandidateBm25Feature,
  CandidateChannelRank,
  CandidateCoverageFeature,
  CandidateFeaturePayload,
  CandidateFieldScore,
  CandidateId,
  CandidateIdentityFeature,
  CandidatePhraseMatch,
  CandidateProximityMatch,
  CandidateRarityFeature,
  CandidateRef,
  CandidateRetrieverSignals,
  CandidateSet,
  CorpusSnapshotId,
  DocumentId,
  EmbeddingSetId,
  ExplainTrace,
  FeatureStore,
  LinkGraphData,
  LinkGraphEdge,
  LinkGraphId,
  LinkGraphNeighbor,
  LinkGraphView,
  PinnedSnapshot,
  RankingConfigTrace,
  RankingFeatureVersion,
  RetrievalCandidate,
  RetrievalQuery,
  RetrievalSnapshotId,
  Retriever,
  RetrieverIdentity,
  RetrieverPlanIdentity,
  RetrieverSignal,
  SegmentId,
  ShardDocRef,
  SnapshotId,
  SnapshotManifestView,
  SnapshotStore,
  SnapshotView,
} from './contracts.js';

export {
  buildEmbeddingSet,
  buildEmbeddingSetFromVectors,
  candidateExecutionProviders,
  computeEmbeddingSetId,
  cosineSimilarity,
  createDenseRetriever,
  createLocalOnnxProviderFromConfig,
  createOnnxSessionWithFallback,
  DENSE_RETRIEVER_VERSION,
  denseAgreementFromCosine,
  DETERMINISTIC_HASH_EMBEDDING_RECIPE_VERSION,
  deterministicHashEmbeddingRecipeIdentity,
  DeterministicHashProvider,
  EMBEDDING_RECIPE_FRESHNESS_ID_VERSION,
  EMBEDDING_SPACE_ID_VERSION,
  EMBEDDING_VECTOR_PROJECTION_VERSION,
  embeddingRecipeFreshnessId,
  embeddingRecipeIdentityForProvider,
  embeddingSpaceIdForRecipe,
  ensureLocalOnnxModelArtifact,
  HUGGINGFACE_TOKENIZERS_RUNTIME_VERSION,
  inspectLocalOnnxModelArtifact,
  LOCAL_ONNX_MODELS,
  LOCAL_ONNX_RECIPE_VERSION,
  LOCAL_ONNX_RENDERED_TEXT_PROJECTION_VERSION,
  localOnnxDataDir,
  localOnnxEmbeddingRecipeIdentity,
  localOnnxManifestPath,
  localOnnxModelArtifactHash,
  localOnnxModelDescriptor,
  localOnnxModelDir,
  localOnnxModelFilePath,
  LocalOnnxProvider,
  localOnnxSessionModelPath,
  localOnnxTokenizerArtifactHash,
  localOnnxTokenizerConfigPath,
  localOnnxTokenizerJsonPath,
  meanPoolLastHiddenState,
  normalizeEmbeddingVector,
  ONNXRUNTIME_NODE_RUNTIME_VERSION,
  renderLocalOnnxEmbeddingInput,
  resolveLocalOnnxModelKey,
  resolveLocalOnnxProviderSelection,
  truncateEncoding,
  VECTOR_GENERATION_MANIFEST_ID_VERSION,
  vectorGenerationIdForManifest,
  vectorProjectionHash,
} from './dense/index.js';

export type {
  BuiltEmbeddingSet,
  DenseEmbeddingRecord,
  DenseEmbeddingSet,
  DenseMetric,
  DenseRetrieverOptions,
  DeterministicHashProviderOptions,
  EmbeddingInputKind,
  EmbeddingProvider,
  EmbeddingProviderIdentity,
  EmbeddingRecipeFreshnessId,
  EmbeddingRecipeIdentity,
  EmbeddingSetDocumentInput,
  EmbeddingSetRecord,
  EmbeddingSpaceId,
  EmbeddingVector,
  LocalOnnxArtifactEnsureOptions,
  LocalOnnxArtifactFile,
  LocalOnnxArtifactFileRole,
  LocalOnnxArtifactInstallResult,
  LocalOnnxArtifactManifest,
  LocalOnnxArtifactState,
  LocalOnnxModelAlias,
  LocalOnnxModelDescriptor,
  LocalOnnxModelKey,
  LocalOnnxProviderOptions,
  LocalOnnxProviderSelection,
  LocalOnnxRuntime,
  LocalOnnxSession,
  LocalOnnxSessionSelection,
  LocalOnnxTensor,
  LocalOnnxTokenizer,
  LocalOnnxTokenizerEncoding,
  OnnxExecutionProvider,
  OnnxExecutionProviderPreference,
} from './dense/index.js';

export { parseMarkdownNote } from './markdown.js';

export type { ParsedMarkdownNote, SearchBuildDocument } from './markdown.js';

export { matchesPathFilter, matchesTagFilter, MAX_SEARCH_QUERY_LENGTH, normalizeSearchParams } from './params.js';

export {
  bm25BoundKey,
  compareCanonicalBm25Terms,
  compareTagOnlyMatches,
  exactDominanceLambda,
  identityScoreFromExactPriority,
  isRankedCandidate,
  nullableRankPriority,
  rankBucketName,
  rerankCandidatesWithSignals,
  rerankScore,
} from './ranking/index.js';

export type {
  CandidateRankSignals,
  ExactDominanceBound,
  ExactDominanceBoundInput,
  RankDocument,
} from './ranking/index.js';

export {
  bm25CorpusStats,
  bm25DocumentFrequency,
  bm25FieldScore,
  bm25TermScore,
  bm25TermScoreFromGlobalStats,
  bm25TermScoreFromStatsLookup,
  bm25TermStats,
  boostedBm25FieldScore,
  buildPositionalPostings,
  buildSearchSnapshotFromSegments,
  canonicalLinkGraphBacklinks,
  canonicalLinkGraphEdges,
  CanonicalSegmentPostingsReader,
  computeFieldBm25Stats,
  computeRetrieverPlanIdentity,
  createFusionRetriever,
  createLinkAdjacencyRetriever,
  createLinkGraphView,
  createPositionalBm25StatsLookup,
  createPositionalRetriever,
  createQueryPostingsLookup,
  createSearchEngine,
  createSearchFieldLengthLookup,
  fieldChannelBm25Boost,
  findPhraseMatches,
  findProximityMatches,
  fuseCandidateSets,
  FUSION_RETRIEVER_VERSION,
  LINK_ADJACENCY_DIRECT_SCORE,
  LINK_ADJACENCY_RETRIEVER_VERSION,
  LINK_ADJACENCY_SCORING_VERSION,
  minimumTermWindow,
  normalizeTerm,
  phraseStartPositions,
  POSITIONAL_FIELD_BY_ID,
  POSITIONAL_FIELD_ID,
  POSITIONAL_RETRIEVER_IDENTITY,
  POSITIONAL_SEARCH_FIELDS,
  positionsForTerm,
  postingKeysForTerms,
  postingsForChannel,
  ProjectionReader,
  proximityScore,
  retrievePositionalCandidates,
  retrieveWithFusion,
  splitCanonicalPostingTerm,
  tokenChannelFusionWeight,
} from './retrieval/index.js';

export type {
  Bm25DocumentFieldInput,
  Bm25DocumentInput,
  Bm25FieldStats,
  Bm25Stats,
  Bm25TermScoreOptions,
  CanonicalDocProjectionDoc,
  CanonicalDocProjectionFieldLength,
  CanonicalDocProjectionIdentityKeys,
  CanonicalDocProjectionOffsets,
  FusionOptions,
  FusionParameters,
  LinkAdjacencyRetrieverOptions,
  PositionalBm25CorpusStats,
  PositionalBm25GlobalStats,
  PositionalBm25StatsLookup,
  PositionalChannelDocumentInput,
  PositionalChannelFieldInput,
  PositionalChannelIndex,
  PositionalDocId,
  PositionalDocumentInput,
  PositionalDocumentRecord,
  PositionalFieldId,
  PositionalFieldInput,
  PositionalPhraseMatch,
  PositionalPosting,
  PositionalPostings,
  PositionalProximityMatch,
  PositionalQueryAnalysis,
  PositionalSnapshotSegmentInput,
  QueryPostingsLookup,
  RankingInput,
  SearchEngine,
  SearchFieldLengthLookup,
  SearchSnapshot,
  SearchSnapshotSegment,
  TermWindow,
} from './retrieval/index.js';

export {
  SEARCH_BOOST,
  SEARCH_DB_SCHEMA,
  SEARCH_FIELD_CHANNEL_BOOST,
  SEARCH_FIELD_CHANNEL_INDEX_PROPERTY,
  SEARCH_FIELD_INDEX_PROPERTY,
  SEARCH_PROPERTIES,
  SEARCH_SCHEMA_DIGEST,
} from './schema.js';

export {
  assertSafeSignedInteger,
  assertSafeUnsignedInteger,
  buildCanonicalSnapshotForTests,
  ByteReader,
  CANONICAL_BM25_STATS_SCHEMA_ID,
  CANONICAL_DOC_PROJECTION_SCHEMA_ID,
  CANONICAL_SEGMENT_MAGIC,
  CANONICAL_SEGMENT_SECTION,
  CANONICAL_SEGMENT_VERSION,
  CANONICAL_TERM_DICTIONARY_SCHEMA_ID,
  canonicalBm25GlobalStatsBytes,
  canonicalBm25GlobalStatsHash,
  canonicalSegmentHash,
  canonicalSegmentSectionBytes,
  canonicalSnapshotManifestBytes,
  canonicalValueBytes,
  corpusSnapshotIdFromManifest,
  decodeCanonicalBm25Section,
  decodeCanonicalSegment,
  decodeCanonicalTermDictionarySection,
  decodeUnsignedLeb128,
  decodeZigZagLeb128,
  encodeCanonicalSegment,
  encodeFloat64Canonical,
  encodeUnsignedLeb128,
  encodeZigZagLeb128,
  lexicalCorpusIdentityFromManifest,
  lookupCanonicalTermDictionaryEntry,
  partitionIdForDocument,
  readCanonicalPostingRow,
  reduceCanonicalBm25GlobalStats,
  snapshotIdFromManifest,
} from './segments/index.js';

export type {
  CanonicalBm25CorpusStats,
  CanonicalBm25FieldStats,
  CanonicalBm25GlobalStats,
  CanonicalBm25GlobalStatsRow,
  CanonicalDocumentRecord,
  CanonicalFieldText,
  CanonicalPartitionDescriptor,
  CanonicalPosting,
  CanonicalSegment,
  CanonicalSnapshotBuildForTestsInput,
  CanonicalSnapshotForTests,
  CanonicalSnapshotManifest,
  CanonicalSnapshotTestDocument,
  CanonicalTermDictionaryEntry,
  Leb128Read,
  LexicalCorpusIdentity,
  SearchCorpusStatsSchemaIdentity,
  SearchModelIdentity,
  SearchScoringModelIdentity,
  SearchSegmentSchemaIdentity,
  SearchSnapshotAnalyzerIdentity,
  SnapshotIdentityTuple,
} from './segments/index.js';
